name: Integration Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    container:
      image: mehaase/agnostic-tests:latest
      volumes:
        - ${{ github.workspace }}:/opt/agnostic
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Start supervisord
      run: /usr/bin/supervisord
    - name: Pause 5 seconds for DB startup
      run: sleep 5
    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org/ | python -
    - name: Add Poetry to PATH
      run: echo "/github/home/.local/bin" >> $GITHUB_PATH
    - name: Run tests
      run: poetry run pytest --cov=agnostic tests/
      env:
        PATH:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
